language: java

sudo: false
install: mvn install
dist: trusty

jdk:
  -oraclejdk11

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

matrix:
  include:
    - env: JDK='Oracle JDK 11'
    - install: . ./install-jdk.sh -F 11 -L BCL

script:
  - mvn test -B
  - echo PATH = ${PATH}
  - echo JAVA_HOME = ${JAVA_HOME}