language: java

sudo: false
install: mvn install
dist: trusty

jdk:
  -oraclejdk11

matrix:
  include:
    - env: JDK='Oracle JDK 11'
    - install: . ./install-jdk.sh -F 11 -L BCL

script:
  - mvn test -B
  - echo PATH = ${PATH}
  - echo JAVA_HOME = ${JAVA_HOME}
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar